### ISSUE TITLE
Can we add custom fonts using `pdfmake-wrapper`?

### ISSUE THREAD

**Issue by ZaLiTHkA** [Lugriz/pdfmake-wrapper#4]
I was about to create my own Angular `provider` for PDF generation when I found this little gem.. :)

but I do have one small issue though, the `pdfmake` implementation that I'm trying to replace makes use of custom fonts, so it loads in a custom `vfs_fonts.js` file generated as per [these instructions](https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/).

I don't see any mention in the readme, so just to check: is it possible to load in custom font definitions while using `pdfmake-wrapper`?

**Comment by ZaLiTHkA** [comment]
maybe I should've just looked through the source code before posting a question... *facepalm* that was a silly one on my part.

since `src/lib/pdfmake-wrapper.ts` starts off with:

```ts
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

I'm going to say the answer to my question above is a resounding no...

---

since my use case here requires a custom `vfs_fonts.js` file, would you (@Lugriz) be willing to consider adjusting this provider to require developers to install and configure `pdfmake` themselves instead?

or perhaps providing a way to override this one point in the initialisation of this provider?

**Comment by Paul75** [comment]
I am interested for this answer ? can or not change font ?

**Comment by Lugriz** [comment]
Now, you can use custom fonts!
Installing the new version 2.0.0.

**Comment by Paul75** [comment]
Hello,

Thanks I test and install pdfmake, @types/pdfmake and your and after in service add : 

PdfMakeWrapper.setFonts(pdfFonts);

but I've got : 

Le module '"pdfmake/build/vfs_fonts"' n'a pas d'exportation par défaut

**Comment by Paul75** [comment]
To works I must declare like : 

```
private readonly pdfFonts: any;

  constructor(private http: HttpClient, private datePipe: DatePipe, private datasService: DatasService) {
    // Set the fonts to use
    this.pdfFonts = require('pdfmake/build/vfs_fonts.js');
    PdfMakeWrapper.setFonts(this.pdfFonts);
  }

```

But when I want to custom : 
`import pdfFonts from "custom/fonts/custom"; // custom fonts`

I can't declare custom not found...

for me I have font in assets like this in my scss :

```
/**************************** Montserrat ****************************/
/* montserrat-regular - cyrillic-ext_latin-ext_latin_vietnamese_cyrillic */
@font-face {
  font-family: "Montserrat";
  font-style: normal;
  font-weight: 400;
  src: url("assets/fonts/Montserrat/montserrat-v14-cyrillic-ext_latin-ext_latin_vietnamese_cyrillic-regular.eot"); /* IE9 Compat Modes */
  src: local("Montserrat Regular"), local("Montserrat-Regular"),
    url("assets/fonts/Montserrat/montserrat-v14-cyrillic-ext_latin-ext_latin_vietnamese_cyrillic-regular.eot?#iefix")
      format("embedded-opentype"),
    /* IE6-IE8 */
      url("assets/fonts/Montserrat/montserrat-v14-cyrillic-ext_latin-ext_latin_vietnamese_cyrillic-regular.woff2")
      format("woff2"),
    /* Super Modern Browsers */
      url("assets/fonts/Montserrat/montserrat-v14-cyrillic-ext_latin-ext_latin_vietnamese_cyrillic-regular.woff")
      format("woff"),
    /* Modern Browsers */
      url("assets/fonts/Montserrat/montserrat-v14-cyrillic-ext_latin-ext_latin_vietnamese_cyrillic-regular.ttf")
      format("truetype"),
    /* Safari, Android, iOS */
      url("assets/fonts/Montserrat/montserrat-v14-cyrillic-ext_latin-ext_latin_vietnamese_cyrillic-regular.svg#Montserrat")
      format("svg"); /* Legacy iOS */
}

/**************************** BARLOW ****************************/

/* barlow-regular - latin-ext_latin_vietnamese */
@font-face {
  font-family: "Barlow";
  font-style: normal;
  font-weight: 400;
  src: url("assets/fonts/Barlow/barlow-v4-latin-ext_latin_vietnamese-regular.eot"); /* IE9 Compat Modes */
  src: local("Barlow Regular"), local("Barlow-Regular"),
    url("assets/fonts/Barlow/barlow-v4-latin-ext_latin_vietnamese-regular.eot?#iefix") format("embedded-opentype"),
    /* IE6-IE8 */ url("assets/fonts/Barlow/barlow-v4-latin-ext_latin_vietnamese-regular.woff2") format("woff2"),
    /* Super Modern Browsers */ url("assets/fonts/Barlow/barlow-v4-latin-ext_latin_vietnamese-regular.woff")
      format("woff"),
    /* Modern Browsers */ url("assets/fonts/Barlow/barlow-v4-latin-ext_latin_vietnamese-regular.ttf") format("truetype"),
    /* Safari, Android, iOS */ url("assets/fonts/Barlow/barlow-v4-latin-ext_latin_vietnamese-regular.svg#Barlow")
      format("svg"); /* Legacy iOS */
}
```

Thanks

**Comment by Paul75** [comment]
I have created vs_fonts.js and add it into the directory of font.

But when I must import it ?

Thanks

**Comment by Lugriz** [comment]
Now, you need to install pdfmake on your own, pdfmake was removed in the lib, the reason is the freedom to use any version and customize the fonts.

install pdfmake
> $ npm install pdfmake --save

and then pdfmake-wrapper
> $ npm install pdfmake-wrapper --save

if you need to use custom fonts, you need to take your font dir, for example: assets/fonts/Montserrat/ and generate the fonts using: [pdfmake-font-generator](https://github.com/Lugriz/pdfmake-wrapper#generate-custom-fonts) and read [how to use custom fonts](https://github.com/Lugriz/pdfmake-wrapper#how-to-use-custom-fonts).

I recommend config your fonts in a bootstrap code, if you are using Angular, use AppModule to configure your fonts.

**Comment by Lugriz** [comment]
Hi! @Paul75 

Now, you need to install pdfmake on your own, pdfmake was removed in the lib, the reason is the freedom to use any version and customize the fonts.

install pdfmake
> $ npm install pdfmake --save

and then pdfmake-wrapper
> $ npm install pdfmake-wrapper --save

if you need to use custom fonts, you need to take your font dir, for example: assets/fonts/Montserrat/ and generate the fonts using: [pdfmake-font-generator](https://github.com/Lugriz/pdfmake-wrapper#generate-custom-fonts) and read [how to use custom fonts](https://github.com/Lugriz/pdfmake-wrapper#how-to-use-custom-fonts).

I recommend config your fonts in a bootstrap code, if you are using Angular, use AppModule to configure your fonts.

**Comment by Paul75** [comment]
Hello,

Sorry but if I do like the document whe  I take same exemple and add : 

import pdfFonts from './pdf/barlow-fonts';

It say me : Could not find a declaration file for module './pdf/barlow-fonts'. 'C:/www/POST_SOC/
ps_client/src/app/domicilies/listing/services/pdf/barlow-fonts.js' implicitly has an 'any' type.

Thanks

**Comment by Paul75** [comment]
Hello,

I solve the errors with add to file typings.d.ts the line (I must test in production, build) : 
declare module '@app/pdf/barlow-fonts.js';

thanks

**Comment by Lugriz** [comment]
@Paul75 can you show me how you are using the lib?

you can use [https://stackblitz.com/](https://stackblitz.com/).

**Comment by Lugriz** [comment]
Check this example in [stackblitz](https://stackblitz.com/edit/angular-tiwpmw?file=src%2Fapp%2Fapp.module.ts)

**Comment by ZaLiTHkA** [comment]
> Now, you can use custom fonts!
> Installing the new version 2.0.0.

thanks @Lugriz, appreciate you taking the time for this one. :)

from the Stackblitz example you linked, I see we still import `vfs_fonts.js`, so I'm assuming to use any proprietary fonts, I'll still need to build a custom `vfs_fonts.js` file to import as per the current PDFMake documentation, correct?

---

either way, I'm a bit busy with a different project at the moment, but I will be coming back to an Ionic/Angular project in the next couple of days that makes use of PDFMake (note: currently still without this wrapper). so I'll go play with this in my sandbox when I get home this evening and see what comes of it.

**Comment by Lugriz** [comment]
@ZaLiTHkA Hi!

I don't know if the documentation is not clear to [generate](https://github.com/Lugriz/pdfmake-wrapper#generate-custom-fonts) and [import](https://github.com/Lugriz/pdfmake-wrapper#how-to-use-custom-fonts) custom fonts, let me know about it.

You need to have font files (not CSS) in some directory, for example:

```text
/myProject
  /fonts
    /custom.ttf
    /custom-bold.ttf
    /custom-italics.ttf
    /custom-bolditalics.ttf
```

and yes, you need to generate an output file from this fonts using [pdfmake-font-generator](https://github.com/Lugriz/pdfmake-font-generator), this tool reads all font files in the specified directory and creates an output file with `.js`extension, this file is what you need to import as your custom fonts, the name of this file does not matter.

*pdfmake* documentation describes to use `gulp buildFonts` to generate the fonts, this force you to install `gulp` and go directly to the package `node_modules/pdfmake`, create `example/fonts`, run `npm install` from `node_modules/pdfmake` and run  `gulp buildFonts` (the reason is because the `gulp`task only generates the fonts if they are in  `example/fonts`). That's the reason I created `pdfmake-font-generator` allow us to generate fonts and save the generated output file wherever we want.

Thanks for using pdfmake-wrapper!

**Comment by ZaLiTHkA** [comment]
> That's the reason I created `pdfmake-font-generator` allow us to generate fonts and save the generated output file wherever we want.

this just keeps getting better.. somehow I completely missed `pdfmake-font-generator`, even with it being mentioned at the end of the project readme.

too many cool toys, not enough time to play with them all.. lol.

**Comment by ZaLiTHkA** [comment]
just a quick follow up on this one: I've just finished up with a few hybrid mobile projects that need to generate one or more PDF documents, each of which import and use a different collection of custom fonts.

without the effort that went into creating both `pdfmake-wrapper` and `pdfmake-font-generator`, I can assure you these same projects would have taken far longer to do...

so here's a massive thank you to @Lugriz for everything, `pdfmake-wrapper` actually makes it pleasant to work with TS code that generates PDF files. ❤️

**Comment by Lugriz** [comment]
I really appreciate your comment, this is a motivation for adding new features to the library and improve it. I'm thinking the possibility to add plugins support. This will be useful to extend the library without affect the core and have tons of plugins (It's the idea) created by the community that add new features and functionalities.

**Comment by ZaLiTHkA** [comment]
> I'm thinking the possibility to add plugins support.

to be completely honest, I'm not sure that would actually be too beneficial for this project.. perhaps this mentality is partly shaped by the fact that it's called "PDFMake Wrapper", but since this is *a wrapper* around another library, I fear we are somewhat limited by what *that library* does.

that said, if we ignore naming for the moment, this project effectively exists to give us two things on an instance of `pdfmake`:

* a nicer way to configure it
* a programmatic API for adding content

while everything else essentially relies on the functionality that `pdfmake` itself provides..

if you want, perhaps you could/should create a new issue with an initial functional design spec for the plugin-oriented idea? then you could discuss ideas and concepts with people who use this project..

---

alternatively, have you considered contacting the two current maintainers of `pdfmake` itself and joining forces? I know their project's current `master` branch has WIP code for a `0.2.x` version, but I haven't looked at the code changes to see which direction it's actually going.

**Comment by Lugriz** [comment]
Thanks for you comment! I will consider those suggestions and re-think the plugins idea.
